=== DavidCG-27/SEW/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud, anchura, fecha, hora, vueltas, localidad, pais, coordenadas, galeriaFotos, galeriaVideos, referencias, tramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT coordenadas (longitudCoordenadas,latitudCoordenadas,altitudCoordenadas)>
<!ELEMENT longitudCoordenadas (#PCDATA)>
<!ELEMENT latitudCoordenadas (#PCDATA)>
<!ELEMENT altitudCoordenadas (#PCDATA)>

<!ELEMENT galeriaFotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto
    nombre CDATA #REQUIRED>

<!ELEMENT galeriaVideos (video*)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video
    nombre CDATA #REQUIRED>

<!ELEMENT referencias (enlace+)>
<!ELEMENT enlace (#PCDATA)>
<!ATTLIST enlace
    url CDATA #REQUIRED>

<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, unidades, sector, latitudTramo, longitudTramos, altitudTramo)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT sector (#PCDATA)>
<!ELEMENT latitudTramo (#PCDATA)>
<!ELEMENT longitudTramos (#PCDATA)>
<!ELEMENT altitudTramo (#PCDATA)>

=== DavidCG-27/SEW/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>    
    <nombre>Circuito callejero de Bakú</nombre>
    <longitud>6003</longitud>
    <anchura>13</anchura>
    <fecha>04/06/2024</fecha>
    <hora>15:00</hora>
    <vueltas>51</vueltas>
    <localidad>Bakú</localidad>
    <pais>Azerbaiyán</pais>
    
    <coordenadas>
        <longitudCoordenadas>49.8533</longitudCoordenadas>
        <latitudCoordenadas>40.3725</latitudCoordenadas> 
        <altitudCoordenadas>-28</altitudCoordenadas> 
    </coordenadas>
    
    <galeriaFotos>
        <foto nombre="aerea_baku.jpg">Fotografía aérea del circuito</foto>
        <foto nombre="tramo_baku.jpg">Fotografía de uno de los tramos</foto>
        <foto nombre="aerea2_baku.jpg">Fotografía del circuito con Baku de fondo</foto>
    </galeriaFotos>
    
    <galeriaVideos>
        <video nombre="choque_stroll_baku.mp4">Choque de Stroll en Bakú</video>
    </galeriaVideos>

    <referencias>
        <enlace url="https://www.dazn.com/es-ES/news/motor/circuito-baku-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-azerbaiyan-mundial-f1/1216g2tjm67qv1vp3xo5ismq36">Ficha del circuito en DAZN</enlace>
        <enlace url="https://es.wikipedia.org/wiki/Circuito_callejero_de_Bakú"> Wikipedia del circuito</enlace>
        <enlace url="https://lebalap.academy/f1/circuito-callejero-de-baku/">Mapa y tramos del circuito</enlace>
    </referencias>
    <tramos>
        <tramo> 
            <distancia>600</distancia>
            <unidades>m</unidades>
            <sector>1</sector>
            <latitudTramo>40.3761408</latitudTramo>
            <longitudTramos>49.8534903</longitudTramos>
            <altitudTramo>-0.5167220</altitudTramo>
        </tramo>
        <tramo>
            <distancia>833</distancia>
            <unidades>m</unidades>
            <sector>1</sector>
            <latitudTramo>40.3740673</latitudTramo>
            <longitudTramos>49.8468675</longitudTramos>
            <altitudTramo>-0.8069524</altitudTramo>
        </tramo>
        <tramo>
            <distancia>1280</distancia>
            <unidades>m</unidades>
            <sector>1</sector>
            <latitudTramo>40.3721799</latitudTramo>
            <longitudTramos>49.8479748</longitudTramos>
            <altitudTramo>-0.8066015</altitudTramo>
        </tramo>
        <tramo>
            <distancia>1435</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3705020</latitudTramo>
            <longitudTramos>49.8431969</longitudTramos>
            <altitudTramo>-0.5107204</altitudTramo>
        </tramo>
        <tramo>
            <distancia>1500</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3697045</latitudTramo>
            <longitudTramos>49.8415996</longitudTramos>
            <altitudTramo>-0.8069058</altitudTramo>
        </tramo>
        <tramo>
            <distancia>1891</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3691145</latitudTramo>
            <longitudTramos>49.8418302</longitudTramos>
            <altitudTramo>-0.5166940</altitudTramo>
        </tramo>
        <tramo>
            <distancia>1921</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3669292</latitudTramo>
            <longitudTramos>49.8382344</longitudTramos>
            <altitudTramo>-0.5167390</altitudTramo>
        </tramo>
        <tramo>
            <distancia>2100</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3671446</latitudTramo>
            <longitudTramos>49.8379858</longitudTramos>
            <altitudTramo>-0.5107283</altitudTramo>
        </tramo>
        <tramo>
            <distancia>2140</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3686267</latitudTramo>
            <longitudTramos>49.8373076</longitudTramos>
            <altitudTramo>-0.5107516</altitudTramo>
        </tramo>
        <tramo>
            <distancia>2211</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3688004</latitudTramo>
            <longitudTramos>49.8368745</longitudTramos>
            <altitudTramo>-0.5107457</altitudTramo>
        </tramo>
        <tramo>
            <distancia>2270</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3688370</latitudTramo>
            <longitudTramos>49.8361886</longitudTramos>
            <altitudTramo>-0.5167025</altitudTramo>
        </tramo>
        <tramo>
            <distancia>2383</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3693945</latitudTramo>
            <longitudTramos>49.8358915</longitudTramos>
            <altitudTramo>-0.5167053</altitudTramo>
        </tramo>
        <tramo>
            <distancia>2700</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3690998</latitudTramo>
            <longitudTramos>49.8346415</longitudTramos>
            <altitudTramo>-0.5166830</altitudTramo>
        </tramo>
        <tramo>
            <distancia>2880</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3679580</latitudTramo>
            <longitudTramos>49.8317620</longitudTramos>
            <altitudTramo>2.3202196</altitudTramo>
        </tramo>
        <tramo>
            <distancia>3120</distancia>
            <unidades>m</unidades>
            <sector>2</sector>
            <latitudTramo>40.3661099</latitudTramo>
            <longitudTramos>49.8308980</longitudTramos>
            <altitudTramo>0.7760836</altitudTramo>
        </tramo>
        <tramo>
            <distancia>3453</distancia>
            <unidades>m</unidades>
            <sector>3</sector>
            <latitudTramo>40.3639394</latitudTramo>
            <longitudTramos>49.8310548</longitudTramos>
            <altitudTramo>-0.5167248</altitudTramo>
        </tramo>
        <tramo>
            <distancia>3651</distancia>
            <unidades>m</unidades>
            <sector>3</sector>
            <latitudTramo>40.3626586</latitudTramo>
            <longitudTramos>49.8346100</longitudTramos>
            <altitudTramo>-0.5166801</altitudTramo>
        </tramo>
        <tramo>
            <distancia>3895</distancia>
            <unidades>m</unidades>
            <sector>3</sector>
            <latitudTramo>40.3641612</latitudTramo>
            <longitudTramos>49.8359150</longitudTramos>
            <altitudTramo>-0.5167437</altitudTramo>
        </tramo>
        <tramo>
            <distancia>4040</distancia>
            <unidades>m</unidades>
            <sector>3</sector>
            <latitudTramo>40.3656773</latitudTramo>
            <longitudTramos>49.8379529</longitudTramos>
            <altitudTramo>-0.5166523</altitudTramo>
        </tramo>
        <tramo>
            <distancia>4433</distancia>
            <unidades>m</unidades>
            <sector>3</sector>
            <latitudTramo>40.3669375</latitudTramo>
            <longitudTramos>49.8384041</longitudTramos>
            <altitudTramo>-0.5167247</altitudTramo>
        </tramo>
        <tramo>
            <distancia>5640</distancia>
            <unidades>m</unidades>
            <sector>3</sector>
            <latitudTramo>40.3690404</latitudTramo>
            <longitudTramos>49.8421578</longitudTramos>
            <altitudTramo>-0.5167119</altitudTramo>
        </tramo>
        <tramo>
            <distancia>6003</distancia>
            <unidades>m</unidades>
            <sector>3</sector>
            <latitudTramo>40.3733657</latitudTramo>
            <longitudTramos>49.8549766</longitudTramos>
            <altitudTramo>-0.5166270</altitudTramo>
        </tramo>
        <tramo> 
            <distancia>6003</distancia>
            <unidades>m</unidades>
            <sector>1</sector>
            <latitudTramo>40.3761408</latitudTramo>
            <longitudTramos>49.8534903</longitudTramos>
            <altitudTramo>-0.5167220</altitudTramo>
        </tramo>
    </tramos>
</circuito>
